### PR TITLE
Update example base on the new implementation of ari.Client

### PR DESCRIPTION
**Pull request by baldrailers**
This change is [Reviewable](https://reviewable.io/reviews/cycoresystems/ari/71)

### CODE REVIEW

**Comment by Ulexus** [comment]
Thanks for the very quick update.  I completely forgot about the examples.

I knew I should have changed the name of `native.New()`.  That now really just creates a new Client, without actually connecting (the websocket) to anything.

This example may actually work, because it doesn't rely on any ARI application (triggered via websocket) being active, I'd prefer to use the new `native.Connect()` in examples, since that should be what most users use.  It combines the creation of the client and its connection.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71#-:-KizR3Kq9n-lWdGvE62T:byamvu)*

**Comment by baldrailers** [comment]
I was just getting started exploring the library. I should check `native.Connect()` instead. Thanks for the feedback. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71#-:-KizRpGz_WB9nnVmp0-6:bg8ajy0)*

**Comment by Ulexus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizSG03U9WZr-wPYj9N:bpgvio7) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
> ```Go
> 	log.Info("Connecting")
> 
> 	cl := native.New(&opts)
> ```

For documentary purposes, let's use `native.Connect(nil)` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by baldrailers** [comment]
*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizUptKlg7zfBCu12aZ:b-aydxgk) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

For documentary purposes, let's use `native.Connect(nil)` here.
</blockquote></details>

`native.Connect()` is expecting some `context`, if I pass `native.Connect(nil, &opts)` this will throw out Segmentation Faults. I wonder what is expected to be in that `ctx` parameter. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by Ulexus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizVi99IUjfDRJIGn4-:btrypq8) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
<details><summary><i>Previously, baldrailers (JAF) wrote…</i></summary><blockquote>

`native.Connect()` is expecting some `context`, if I pass `native.Connect(nil, &opts)` this will throw out Segmentation Faults. I wonder what is expected to be in that `ctx` parameter. 
</blockquote></details>

Yes, the new version of the ARI client uses the context for lifecycle control.  When/if that context is closed, the client will be closed, as well.  For this example, you can use `context.TODO()`(context here is the Go 1.7-introduced `context` package; or for earlier versions of Go, the `x/net/context`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by Ulexus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizWkCVCo3eNaZKkfaL:b1dp0r) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

Yes, the new version of the ARI client uses the context for lifecycle control.  When/if that context is closed, the client will be closed, as well.  For this example, you can use `context.TODO()`(context here is the Go 1.7-introduced `context` package; or for earlier versions of Go, the `x/net/context`)
</blockquote></details>

Looking at it, though, I'm not sure why we are exposing it here.  The native client doesn't actually use it for anything _other_ than lifecycle control, and it has a perfectly good `Close()` function.  I'll rewrite this to not require a context to be passed in.  It seems rather silly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by Ulexus** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizYEAOOt7GvFnK8jTM:b4twqrk) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

Looking at it, though, I'm not sure why we are exposing it here.  The native client doesn't actually use it for anything _other_ than lifecycle control, and it has a perfectly good `Close()` function.  I'll rewrite this to not require a context to be passed in.  It seems rather silly.
</blockquote></details>

Okay, `Connect()` no longer expects a context to be passed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by baldrailers** [comment]
*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizYbJSSWcQzyefq79o:b-ro7zof) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

Okay, `Connect()` no longer expects a context to be passed.
</blockquote></details>

But I just made some updates base on your recommendations ;) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by Ulexus** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizYqjoHdx4Bg3QxFLE:b-p9h52h) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
<details><summary><i>Previously, baldrailers (JAF) wrote…</i></summary><blockquote>

But I just made some updates base on your recommendations ;) 
</blockquote></details>

Ah, I'm sorry.   I just saw that, and it didn't make any sense to me why we were requesting a context to be passed in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by Ulexus** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizZCp4VGSe47L97i8T:b-zdl4m7) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

Ah, I'm sorry.   I just saw that, and it didn't make any sense to me why we were requesting a context to be passed in.
</blockquote></details>

I'm putting the keyboard down, now... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by baldrailers** [comment]
*[_examples/helloworld/main.go, line 34 at r1](https://reviewable.io:443/reviews/cycoresystems/ari/71#-KizSG02tXeZA42HBl-a:-KizZOyZa74cQ6Pl9UPT:b-9o31s2) ([raw file](https://github.com/cycoresystems/ari/blob/feab2da1155b180f618fb785cb3b2d72c6ab6ffb/_examples/helloworld/main.go#L34)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

I'm putting the keyboard down, now... 
</blockquote></details>

Yeah no worries, I will just watch the upstream and update the example accordingly. You may stumble into something even deeper when you removed the context. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by Ulexus** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/ari/71)*

**Comment by Ulexus** [comment]
Thanks for the contribution!

**Pull request merged**
